# %%
import sys
sys.path.append('/home/nam_07/projects/AML_work_study/AML_work_study')
sys.path.append('/home/nam_07/projects/AML_work_study/AML_work_study/analysis/lib')

import re
from pathlib import Path
from analysis_functions import get_experiment_path
from scenarios import SCENARIO_KWARGS, BOOST_SCENARIO_KWARGS

OUT_PATH = Path('/home/nam_07/projects/AML_work_study/writing/Experimental-Protocol/tables/data/run_overview.tex')


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def latest_run(path_str):
    """Return LaTeX-formatted latest timestamp folder name, or '---' if absent."""
    p = Path(path_str)
    if not p.exists():
        return '---'
    ts = re.compile(r'^\d{8}_\d{6}$')
    runs = sorted(d.name for d in p.iterdir() if d.is_dir() and ts.match(d.name))
    escaped = runs[-1].replace('_', r'\_')
    return f'\\texttt{{{escaped}}}' if runs else '---'


def paths(comparable_only=False, **kwargs):
    """Return (comparable_path, system_path | None) for the given experiment kwargs."""
    c = get_experiment_path(eval_mode='comparable', **kwargs)
    s = None if comparable_only else get_experiment_path(eval_mode='system', **kwargs)
    return c, s


# Scenario kwargs come from the shared registry (analysis/lib/scenarios.py) so this
# provenance table can't drift out of sync with what the results/pattern_analysis
# scripts actually use. H0 has no entry of its own — it's defined as "= F1".
_ALL_KWARGS = {**SCENARIO_KWARGS, **BOOST_SCENARIO_KWARGS, "H0": SCENARIO_KWARGS["F1"]}


def row(sid, desc, comparable_only=False):
    """Build a (id, description, comparable_path, system_path) GROUPS row.
    `desc` is this table's own prose (more detailed than scenarios.py's SCENARIO_NAMES,
    which are compact labels for results tables) — kwargs are shared, descriptions aren't."""
    c, s = paths(comparable_only=comparable_only, **_ALL_KWARGS[sid])
    return (sid, desc, c, s)


# --------------------------------------------------------------------------- #
# Scenario definitions
# --------------------------------------------------------------------------- #

GROUPS = [
    ("Baselines", [
        row("S1", r"Full-info GNN (R0, BN)"),
        row("S2", r"Full-info GNN (R1, LN)"),
        row("S3", r"Individual GNN (batching)"),
        row("S4", r"Individual GNN (full batch)"),
        row("B1", r"XGBoost full-info (R0, IBM FE)"),
        row("B2", r"XGBoost full-info (R1)"),
        row("B3", r"XGBoost individual (R1)"),
        row("B4", r"SecureBoost (SplitFed)", comparable_only=True),
        row("F1", r"FedAvg baseline"),
        row("P2", r"FedProx ($\mu=0.1$)"),
        row("V1", r"SplitFed (FedGraphSimple)"),
    ]),
    ("FedAvg sensitivity", [
        row("F0", r"FedSGD-like (uniform, $C{=}1.0$, $E{=}1$, no batch)"),
        row("F1", r"Baseline FedAvg"),
        row("F2", r"Batch size $B{=}4096$"),
        row("F3", r"Full batch (no mini-batch)"),
        row("F4", r"Local epochs $E{=}1$"),
        row("F5", r"Local epochs $E{=}10$"),
        row("F6", r"Local epochs $E{=}25$ (stress)"),
        row("F7", r"Client fraction $C{=}0.25$"),
        row("F8", r"Client fraction $C{=}0.50$"),
        row("F9", r"Uniform weighting"),
        row("F10", r"$T{=}50$ communication rounds"),
    ]),
    ("FedProx sensitivity", [
        row("P1", r"FedProx ($\mu=0.01$)"),
        row("P2", r"FedProx ($\mu=0.1$)"),
        row("P3", r"FedProx ($\mu=1.0$)"),
    ]),
    (r"Heterogeneity experiments (relative to baseline F1/H0)", [
        row("H0", r"Baseline (= F1)"),
        row("H1", r"Remove top-10 training parties"),
        row("H2", r"Remove top-1 training party"),
        row("H3", r"Remove bottom-10 training parties"),
        row("H4", r"Remove bottom-5\% training parties"),
        row("H5", r"Loss weights $[1, 1]$ (no class weight)"),
        row("H6", r"Loss weights $[1, 980]$ (inv.\ freq.)"),
        row("H7", r"Loss weights $[1, 50]$ (clipped inv.\ freq.)"),
        row("H8", r"Currency normalisation"),
    ]),
]


# --------------------------------------------------------------------------- #
# Table generation
# --------------------------------------------------------------------------- #

def build_table(groups):
    lines = []
    lines.append(r'% Auto-generated by generate_run_overview_table.py — do not edit by hand.')
    lines.append(r'% Path root: experiments/small_HI/split_0.6_0.2/{comparable|system}/...')
    lines.append(r'% Timestamps show the latest run folder; load_results.py picks the most recent.')
    lines.append(r'\begin{tabular}{llll}')
    lines.append(r'\toprule')
    lines.append(r'\textbf{ID} & \textbf{Description} & \textbf{Comparable run} & \textbf{System run} \\')

    for group_name, rows in groups:
        lines.append(r'\midrule')
        lines.append(rf'\multicolumn{{4}}{{l}}{{\textit{{{group_name}}}}} \\')
        for r in rows:
            exp_id, desc, c_path, s_path = r
            c_run = latest_run(c_path)
            s_run = latest_run(s_path) if s_path is not None else '---'
            lines.append(rf'{exp_id} & {desc} & {c_run} & {s_run} \\')

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    return '\n'.join(lines) + '\n'


# %%

table_tex = build_table(GROUPS)
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
OUT_PATH.write_text(table_tex)
print(f"Saved: {OUT_PATH}")

# %%
